# Online Retail Data Pipeline

This notebook processes retail transaction data through Bronze → Silver → Golden layers and loads it into SQL Server for analysis.

**Stages:**
1. **Bronze Layer**: Raw data import and initial exploration
2. **Silver Layer**: Data cleaning and type conversion
3. **Golden Layer**: Final dataset split into Sales, Refunds, and Discounts tables
4. **Database**: Upload cleaned data to SQL Server

In [1]:
# ============================================
# BRONZE LAYER: IMPORTS & RAW DATA LOADING
# ============================================

import pandas as pd
import numpy as np

In [2]:
# Load raw retail transaction data from CSV
df_bronze = pd.read_csv('online_retail_II.csv')

In [3]:
# Display raw dataset
df_bronze

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [4]:
# Check data structure and data types
df_bronze.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  str
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 65.1 MB

In [5]:
# Display statistical summary of numeric columns
df_bronze.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

## SILVER LAYER: FINAL CLEANED DATA

In [6]:
# Create silver layer copy and optimize data types
df_silver = df_bronze

In [7]:
# Convert to optimal pandas data types (nullable types)
df_silver = df_silver.convert_dtypes()

In [8]:
# Verify optimized data types in silver layer
df_silver.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  string
 1   StockCode    1067371 non-null  string
 2   Description  1062989 non-null  string
 3   Quantity     1067371 non-null  Int64
 4   InvoiceDate  1067371 non-null  string
 5   Price        1067371 non-null  Float64
 6   Customer ID  824364 non-null   Int64
 7   Country      1067371 non-null  string
dtypes: Float64(1), Int64(2), string(5)
memory usage: 68.2 MB

In [9]:
# Display statistical summary of silver layer
df_silver.describe()

         Quantity       Price   Customer ID
count   1067371.0   1067371.0      824364.0
mean     9.938898    4.649388  15324.638504
std    172.705794  123.553059    1697.46445
min      -80995.0   -53594.36       12346.0
25%           1.0        1.25       13975.0
50%           3.0         2.1       15255.0
75%          10.0        4.15       16797.0
max       80995.0     38970.0       18287.0

In [10]:
# Display sample of cleaned data
df_silver.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
210323,509739,22418,10 COLOUR SPACEBOY PEN,48,2010-05-25 12:46:00,0.85,13266,United Kingdom
11360,490300,22073,RETRO SPOT STORAGE JAR,1,2009-12-04 14:19:00,3.75,12970,United Kingdom
816942,562455,16156S,WRAP PINK FAIRY CAKES,25,2011-08-05 10:32:00,0.42,18097,United Kingdom
793145,560359,22396,MAGNETS PACK OF 4 RETRO PHOTO,1,2011-07-18 11:47:00,0.39,14159,United Kingdom
988448,576051,21156,RETROSPOT CHILDRENS APRON,8,2011-11-13 14:45:00,1.95,14911,EIRE

In [11]:
# Remove rows with missing values and check updated structure
df_silver = df_silver.dropna()
df_silver.info()

<class 'pandas.DataFrame'>
Index: 824364 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      824364 non-null  string
 1   StockCode    824364 non-null  string
 2   Description  824364 non-null  string
 3   Quantity     824364 non-null  Int64
 4   InvoiceDate  824364 non-null  string
 5   Price        824364 non-null  Float64
 6   Customer ID  824364 non-null  Int64
 7   Country      824364 non-null  string
dtypes: Float64(1), Int64(2), string(5)
memory usage: 59.0 MB

In [12]:
# Identify any remaining negative quantities in silver layer
df_silver[df_silver['Quantity'] <= 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.1,16321,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321,Australia
...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397,United Kingdom
1067002,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498,United Kingdom
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311,United Kingdom
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315,United Kingdom

## SILVER LAYER: FINAL CLEANED DATA

In [14]:
# Create golden layer (final clean dataset)
df_golden = df_silver
df_golden

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.1,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.1,12680,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.0,12680,France

In [15]:
# Verify cleaned data structure
df_golden.info()

<class 'pandas.DataFrame'>
Index: 824364 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      824364 non-null  string
 1   StockCode    824364 non-null  string
 2   Description  824364 non-null  string
 3   Quantity     824364 non-null  Int64
 4   InvoiceDate  824364 non-null  string
 5   Price        824364 non-null  Float64
 6   Customer ID  824364 non-null  Int64
 7   Country      824364 non-null  string
dtypes: Float64(1), Int64(2), string(5)
memory usage: 59.0 MB

## DATA SPLITTING: Categorize into Sales, Refunds, and Discounts

In [16]:
# Extract sales transactions (positive quantity)
sales_df = df_golden[df_golden['Quantity'] > 0]
sales_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.1,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.1,12680,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.0,12680,France

In [17]:
# Extract refund transactions (negative quantity)
refund_df = df_golden[df_golden['Quantity'] < 0]
refund_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.1,16321,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321,Australia
...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397,United Kingdom
1067002,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498,United Kingdom
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311,United Kingdom
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315,United Kingdom

In [18]:
# Convert negative quantities to positive for clarity in refunds table
refund_df['Quantity'] = refund_df['Quantity'] * -1
refund_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,12,2009-12-01 10:33:00,2.95,16321,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,6,2009-12-01 10:33:00,1.65,16321,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,4,2009-12-01 10:33:00,4.25,16321,Australia
181,C489449,21896,POTTING SHED TWINE,6,2009-12-01 10:33:00,2.1,16321,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,12,2009-12-01 10:33:00,2.95,16321,Australia
...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,11,2011-12-09 09:57:00,0.83,14397,United Kingdom
1067002,C581499,M,Manual,1,2011-12-09 10:28:00,224.69,15498,United Kingdom
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,5,2011-12-09 11:57:00,10.95,15311,United Kingdom
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,1,2011-12-09 11:58:00,1.25,17315,United Kingdom
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,5,2011-12-09 11:58:00,1.25,17315,United Kingdom

In [19]:
# Display refund data with refund money column
refund_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,12,2009-12-01 10:33:00,2.95,16321,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,6,2009-12-01 10:33:00,1.65,16321,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,4,2009-12-01 10:33:00,4.25,16321,Australia
181,C489449,21896,POTTING SHED TWINE,6,2009-12-01 10:33:00,2.1,16321,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,12,2009-12-01 10:33:00,2.95,16321,Australia
...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,11,2011-12-09 09:57:00,0.83,14397,United Kingdom
1067002,C581499,M,Manual,1,2011-12-09 10:28:00,224.69,15498,United Kingdom
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,5,2011-12-09 11:57:00,10.95,15311,United Kingdom
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,1,2011-12-09 11:58:00,1.25,17315,United Kingdom
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,5,2011-12-09 11:58:00,1.25,17315,United Kingdom

In [20]:
# Calculate total profit from sales (Quantity × Price)
sales_df['Profit'] = sales_df['Quantity'] * sales_df['Price']

In [21]:
# Display sales data with profit column
sales_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Profit
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.1,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0
...,...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.1,12680,France,12.6
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.6
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.6
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.0,12680,France,18.0

In [22]:
# Calculate total refund amount (Quantity × Price)
refund_df['Refund Money'] = refund_df['Quantity'] * refund_df['Price']
refund_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Refund Money
178,C489449,22087,PAPER BUNTING WHITE LACE,12,2009-12-01 10:33:00,2.95,16321,Australia,35.4
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,6,2009-12-01 10:33:00,1.65,16321,Australia,9.9
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,4,2009-12-01 10:33:00,4.25,16321,Australia,17.0
181,C489449,21896,POTTING SHED TWINE,6,2009-12-01 10:33:00,2.1,16321,Australia,12.6
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,12,2009-12-01 10:33:00,2.95,16321,Australia,35.4
...,...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,11,2011-12-09 09:57:00,0.83,14397,United Kingdom,9.13
1067002,C581499,M,Manual,1,2011-12-09 10:28:00,224.69,15498,United Kingdom,224.69
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,5,2011-12-09 11:57:00,10.95,15311,United Kingdom,54.75
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,1,2011-12-09 11:58:00,1.25,17315,United Kingdom,1.25
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,5,2011-12-09 11:58:00,1.25,17315,United Kingdom,6.25

In [23]:
# Extract discount/promotional transactions (price = 0)
discount_df = df_golden[df_golden['Price'] == 0]
discount_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126,United Kingdom
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658,United Kingdom
16107,490727,M,Manual,1,2009-12-07 16:38:00,0.0,17231,United Kingdom
18738,490961,22065,CHRISTMAS PUDDING TRINKET POT,1,2009-12-08 15:25:00,0.0,14108,United Kingdom
18739,490961,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-08 15:25:00,0.0,14108,United Kingdom
...,...,...,...,...,...,...,...,...
1004540,577129,22464,HANGING METAL HEART LANTERN,4,2011-11-17 19:52:00,0.0,15602,United Kingdom
1005014,577168,M,Manual,1,2011-11-18 10:42:00,0.0,12603,Germany
1006110,577314,23407,SET OF 2 TRAYS HOME SWEET HOME,2,2011-11-18 13:23:00,0.0,12444,Norway
1011446,577696,M,Manual,1,2011-11-21 11:57:00,0.0,16406,United Kingdom
1027583,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.0,13256,United Kingdom

In [24]:
# Display sample of discount transactions
discount_df.sample(6)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
972254,574920,22899,CHILDREN'S APRON DOLLY GIRL,1,2011-11-07 16:34:00,0.0,13985,United Kingdom
612250,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,2011-02-10 13:08:00,0.0,17560,United Kingdom
887286,568384,M,Manual,1,2011-09-27 09:46:00,0.0,12748,United Kingdom
565550,539722,22423,REGENCY CAKESTAND 3 TIER,10,2010-12-21 13:45:00,0.0,14911,EIRE
364333,524701,22218,CAKE STAND LACE WHITE,2,2010-09-30 12:19:00,0.0,17667,United Kingdom
327801,521375,22202,MILK PAN PINK RETROSPOT,3,2010-09-05 11:58:00,0.0,12647,Germany

In [ ]:
# Calculate average price per product (StockCode) and map to discount items
# shows what the typical price should have been for discounted items
avg_prices = df_golden.groupby('StockCode')['Price'].mean().round(2)
discount_df['Average Price'] = discount_df['StockCode'].map(avg_prices)
discount_df[discount_df['Average Price'] == 'M']

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country, Average Price]
Index: []

In [26]:
# Display discount data with average price mapping
discount_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Average Price
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126,United Kingdom,1.54
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658,United Kingdom,7.46
16107,490727,M,Manual,1,2009-12-07 16:38:00,0.0,17231,United Kingdom,427.24
18738,490961,22065,CHRISTMAS PUDDING TRINKET POT,1,2009-12-08 15:25:00,0.0,14108,United Kingdom,1.04
18739,490961,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-08 15:25:00,0.0,14108,United Kingdom,1.48
...,...,...,...,...,...,...,...,...,...
1004540,577129,22464,HANGING METAL HEART LANTERN,4,2011-11-17 19:52:00,0.0,15602,United Kingdom,1.62
1005014,577168,M,Manual,1,2011-11-18 10:42:00,0.0,12603,Germany,427.24
1006110,577314,23407,SET OF 2 TRAYS HOME SWEET HOME,2,2011-11-18 13:23:00,0.0,12444,Norway,9.85
1011446,577696,M,Manual,1,2011-11-21 11:57:00,0.0,16406,United Kingdom,427.24
1027583,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.0,13256,United Kingdom,0.68

## Upload to SSMS

In [27]:
# ========================================
# DATABASE LAYER: Upload to SQL Server
# ========================================

from sqlalchemy import create_engine
import urllib

In [28]:
# Configure SQL Server connection details
server = r'DESKTOP-8N5RPBA\MSSQLSERVER01'  # Local SQL Server instance
database = 'Retail'  # Target database

In [29]:
# Create SQLAlchemy engine with Windows authentication
connection_string = f'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};Trusted_Connection=yes;'
params = urllib.parse.quote_plus(connection_string)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [30]:
# Write Sales data to SQL Server (replace if exists)
sales_df.to_sql('Sales', con=engine, schema='Golden', if_exists='replace', index=False)

139

In [ ]:
# Write Refund data to SQL Server (replace if exists)
refund_df.to_sql('Refund', con=engine, schema='Golden', if_exists='replace', index=False)

104

In [ ]:
# Write Discount data to SQL Server (replace if exists)
discount_df.to_sql('Discounts', con=engine, schema='Golden', if_exists='replace', index=False)

71

In [ ]:
# Summary: Row counts for each dataset
print("Refund transactions:")
len(refund_df)

18744

In [ ]:
print("Sales transactions:")
len(sales_df)

805620

In [ ]:
print("Discount transactions:")
len(discount_df)

71